"""Apply assessment results to claims.csv."""
import csv
import json

results = [
  {"row_index":0,"assessment":"Red","badge_label":"Not supported by cited case","brief_text":"Under Rule 8(b)(6), denials must fairly respond to the substance of the allegation; a party cannot deny facts established by undisputed documentary evidence or already admitted in prior pleadings","opinion_text":"Swierkiewicz v. Sorema is about whether an employment discrimination complaint must plead a prima facie case under McDonnell Douglas. The Court held that Rule 8(a)(2) short and plain statement standard applies. The opinion discusses Rule 8(a), 8(e)(1), and 8(f) but never addresses Rule 8(b)(6) or the standards for denials in responsive pleadings.","explanation":"This case is entirely about the sufficiency of complaint pleading under Rule 8(a), not about the adequacy of denials under Rule 8(b)(6). The quoted text does not appear in the opinion."},
  {"row_index":1,"assessment":"Red","badge_label":"Not supported by cited case","brief_text":"A party cannot claim lack of knowledge about facts within the partys own knowledge or control.","opinion_text":"David v. Caterpillar is a Title VII employment discrimination case about retaliation. The opinion addresses jury instructions, sufficiency of evidence, and punitive damages. It does not discuss Rule 8(b) denial standards.","explanation":"This opinion addresses Title VII retaliation, not pleading standards. The quoted language does not appear in the opinion."},
  {"row_index":2,"assessment":"Red","badge_label":"Not supported by cited case","brief_text":"A party may not deny on information and belief matters within its personal knowledge or control.","opinion_text":"Sojka v. Bovis Lend Lease is about summary judgment procedure under Rule 56, not pleading denial standards.","explanation":"This case concerns summary judgment procedure. It does not address Rule 8(b) denials. The quoted language does not appear in the opinion."},
  {"row_index":4,"assessment":"Yellow","badge_label":"Overstated -- case partially supports","brief_text":"Judicial admissions in pleadings are binding and may not be controverted at trial absent leave to amend.","opinion_text":"The court held that a party cannot attack issues of fact established in admissions by resisting a motion for summary judgment and that Rule 36(b) provides that a matter admitted is conclusively established.","explanation":"Kasuboski supports the principle that admissions are binding, but addresses Rule 36 admissions (unanswered requests), not judicial admissions in pleadings. The quoted language is a paraphrase."},
  {"row_index":6,"assessment":"Red","badge_label":"Quote not found in opinion","brief_text":"Where a defendant admits the underlying facts but denies the legal conclusion, the factual admissions control.","opinion_text":"Iqbal v. Hasty (2d Cir. 2007) addresses qualified immunity and pleading standards in a post-9/11 detention case. It does not contain the quoted language or any discussion of factual admissions controlling over legal denials.","explanation":"The quoted text does not appear in the opinion. Iqbal v. Hasty is a qualified immunity case about post-9/11 detention conditions."},
  {"row_index":7,"assessment":"Red","badge_label":"Citation resolves to different case","brief_text":"Denying facts established by documentary evidence violates Rule 11.","opinion_text":"The opinion file is Argue v. David Davis Enterprises, Inc., a 2009 E.D. Pa. attorneys fees order. It is not Kraemer v. Franklin and Marshall College.","explanation":"CourtListener matched this citation to an entirely different case. The proposition cannot be verified."},
  {"row_index":8,"assessment":"Green","badge_label":"Supported","brief_text":"When opposing parties tell two different stories, one of which is blatantly contradicted by the record, so that no reasonable jury could believe it, a court should not adopt that version of the facts.","opinion_text":"When opposing parties tell two different stories, one of which is blatantly contradicted by the record, so that no reasonable jury could believe it, a court should not adopt that version of the facts for purposes of ruling on a motion for summary judgment.","explanation":"Close match -- the opinion includes a trailing phrase the brief omits. The minor omission does not alter the meaning."},
  {"row_index":9,"assessment":"Red","badge_label":"Quote not found in opinion","brief_text":"Video evidence that conclusively disproves a partys account defeats that account as a matter of law.","opinion_text":"Whitlock v. Brueggemann (7th Cir. 2012) is a wrongful conviction case about fabricated evidence and coerced testimony. It does not discuss video evidence defeating a partys account and does not cite Scott v. Harris.","explanation":"The quoted text is fabricated. The Whitlock case involves wrongful murder convictions, not video evidence. The proposition is actually the holding of Scott v. Harris."},
  {"row_index":10,"assessment":"Red","badge_label":"Not supported by cited case","brief_text":"When the documentary evidence makes clear that the allegations in the complaint could not have occurred as alleged, those allegations must be disregarded.","opinion_text":"Anderson v. Branen holds that all law enforcement officials have an affirmative duty to intervene to protect the constitutional rights of citizens from infringement by other law enforcement officers in their presence. The case addresses the duty to intercede and excessive force.","explanation":"The quoted text does not appear in the opinion. Anderson v. Branen is about officers duty to intervene. Both the quote and proposition are fabricated attributions."},
  {"row_index":11,"assessment":"Yellow","badge_label":"Reworded -- not a verbatim quote","brief_text":"obvious reasons to doubt the truth of what he or she is asserting.","opinion_text":"McMurtreys Franks motion permitted a reasonable inference of falsity because it provided obvious reasons to doubt the veracity of the allegations (quoting United States v. Whitley).","explanation":"The opinion uses obvious reasons to doubt the veracity (quoting Whitley), not the truth of what he or she is asserting. The proposition is supported but the quoted phrase is reworded."},
  {"row_index":12,"assessment":"Red","badge_label":"Not supported by cited case","brief_text":"A party cannot claim lack of knowledge about facts within the partys own knowledge or control.","opinion_text":"David v. Caterpillar is a Title VII case. It does not discuss pleading standards or denial requirements under Rule 8(b).","explanation":"Same opinion as Row 1. Title VII case with no discussion of Rule 8(b). The quoted language is fabricated."},
  {"row_index":13,"assessment":"Green","badge_label":"Supported","brief_text":"When opposing parties tell two different stories, one of which is blatantly contradicted by the record, so that no reasonable jury could believe it, a court should not adopt that version of the facts.","opinion_text":"When opposing parties tell two different stories, one of which is blatantly contradicted by the record, so that no reasonable jury could believe it, a court should not adopt that version of the facts for purposes of ruling on a motion for summary judgment.","explanation":"Same quote and opinion as Row 8. Close match with minor trailing omission."},
  {"row_index":14,"assessment":"Green","badge_label":"Supported","brief_text":"material either to guilt or to punishment.","opinion_text":"We now hold that the suppression by the prosecution of evidence favorable to an accused upon request violates due process where the evidence is material either to guilt or to punishment, irrespective of the good faith or bad faith of the prosecution.","explanation":"The quoted phrase appears verbatim. The proposition accurately states the Brady holding."},
  {"row_index":15,"assessment":"Green","badge_label":"Supported","brief_text":"Good faith is inconsistent with knowingly or recklessly swearing false statements into warrant affidavits","opinion_text":"We hold that, where the defendant makes a substantial preliminary showing that a false statement knowingly and intentionally, or with reckless disregard for the truth, was included by the affiant in the warrant affidavit, the Fourth Amendment requires that a hearing be held.","explanation":"Franks v. Delaware holds that knowingly or recklessly false statements in warrant affidavits can void the warrant. The proposition is a reasonable characterization."},
  {"row_index":16,"assessment":"Green","badge_label":"Supported","brief_text":"knowingly violating the law.","opinion_text":"As the qualified immunity defense has evolved, it provides ample protection to all but the plainly incompetent or those who knowingly violate the law.","explanation":"The quoted phrase appears verbatim at page 341."},
  {"row_index":17,"assessment":"Yellow","badge_label":"Reworded -- not a verbatim quote","brief_text":"Individual-capacity suits for damages under Section 1983 are not barred by the Eleventh Amendment.","opinion_text":"We hold that state officials, sued in their individual capacities, are persons within the meaning of Section 1983. The Eleventh Amendment does not bar such suits.","explanation":"The proposition is well-supported but the brief presents it as a direct quote when it is actually a paraphrase."},
  {"row_index":18,"assessment":"Yellow","badge_label":"Overstated -- case partially supports","brief_text":"Intentional torts such as false arrest and malicious prosecution fall outside ITCA protection","opinion_text":"Wilson v. Isaacs addresses the ITCAs law enforcement immunity exception for false arrest/false imprisonment, and holds that excessive force claims are not shielded. The case does not address malicious prosecution.","explanation":"Wilson v. Isaacs addresses false arrest but not malicious prosecution. The brief overstates the scope."},
  {"row_index":19,"assessment":"Green","badge_label":"Supported","brief_text":"State notice-of-claim statutes are preempted when applied to federal Section 1983 actions","opinion_text":"Because the notice-of-claim statute at issue here conflicts in both its purpose and effects with the remedial objectives of Section 1983, we conclude that the state law is pre-empted.","explanation":"Felder v. Casey squarely holds this."},
  {"row_index":20,"assessment":"Green","badge_label":"Supported","brief_text":"Video evidence defeats contradictory account under Scott v. Harris standard","opinion_text":"Respondents version of events is so utterly discredited by the record that no reasonable jury could have believed him.","explanation":"Scott v. Harris establishes that video evidence contradicting a partys account defeats it at summary judgment."},
  {"row_index":23,"assessment":"Green","badge_label":"Supported","brief_text":"Material falsehood in warrant affidavit, made knowingly or with reckless disregard for truth, voids the warrant","opinion_text":"If the allegation of perjury or reckless disregard is established by a preponderance, and the remaining content is insufficient for probable cause, the search warrant must be voided and the fruits excluded.","explanation":"The Franks holding directly supports this proposition."},
  {"row_index":24,"assessment":"Red","badge_label":"Not supported by cited case","brief_text":"Probable cause dissipates when officers receive exculpatory evidence yet fail to act.","opinion_text":"Beauchamp holds the opposite: once an officer learns sufficient trustworthy information establishing probable cause, he is entitled to rely on what he knows and is under no further duty to investigate. The word dissipates does not appear in the opinion.","explanation":"The brief presents a fabricated quotation and attributes a principle that the case explicitly rejects. Beauchamp affirmed summary judgment for the officers, holding that probable cause persisted. The case stands for the opposite proposition."},
  {"row_index":25,"assessment":"Green","badge_label":"Supported","brief_text":"No qualified immunity where officer knowingly violates clearly established law","opinion_text":"Qualified immunity provides ample protection to all but the plainly incompetent or those who knowingly violate the law.","explanation":"The Malley opinion directly supports this proposition."},
  {"row_index":26,"assessment":"Red","badge_label":"Citation resolves to different case","brief_text":"Malice may be inferred from advancing charges in the face of contrary facts.","opinion_text":"The opinion file is Abbott v. State, 371 N.E.2d 721 (Ind. Ct. App. 1978), a criminal appeal about entering to commit a felony. It contains no discussion of malice or malicious prosecution.","explanation":"CourtListener matched this to Abbott v. State, a completely different case. The proposition cannot be verified."},
  {"row_index":27,"assessment":"Green","badge_label":"Supported","brief_text":"Malice may also be inferred from the facts which, if established, would constitute want of probable cause.","opinion_text":"Dwyer v. McClean, Instruction No. 7: Malice may also be inferred from the facts which, if established, would constitute want of probable cause.","explanation":"The quoted language appears verbatim. The proposition is directly supported."},
  {"row_index":28,"assessment":"Red","badge_label":"Citation resolves to different case","brief_text":"Denying facts established by documentary evidence violates Rule 11.","opinion_text":"Same as Row 7: the opinion file is Argue v. David Davis Enterprises, not Kraemer v. Franklin and Marshall College.","explanation":"Same mismatched opinion as Row 7. The quoted text and proposition cannot be verified."},
]

with open("briefs/maxwell-v-michael/claims.csv", newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    fieldnames = list(reader.fieldnames)
    rows = list(reader)

for col in ["assessment", "supporting_language", "badge_label", "brief_text", "opinion_text", "explanation"]:
    if col not in fieldnames:
        fieldnames.append(col)

for r in results:
    idx = r["row_index"]
    rows[idx]["assessment"] = r["assessment"]
    rows[idx]["badge_label"] = r.get("badge_label", "")
    rows[idx]["brief_text"] = r.get("brief_text", "")
    rows[idx]["opinion_text"] = r.get("opinion_text", "")
    rows[idx]["explanation"] = r.get("explanation", "")
    rows[idx]["supporting_language"] = r.get("opinion_text", "")

missing = [i for i, row in enumerate(rows) if not row.get("assessment")]
if missing:
    print("WARNING: rows missing assessment:", missing)
else:
    print("All 29 rows have assessments")

with open("briefs/maxwell-v-michael/claims.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

from collections import Counter
counts = Counter(row["assessment"] for row in rows)
print("Assessment summary:", dict(counts))
